// <auto-generated />
namespace FossTechCrm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addContactTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addContactTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201907201958475_addContactTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
